#!/bin/bash
DATE="$(date +'%F')"

echo $DATE 

#chromium-browser --headless --proxy-server="socks://localhost:8118" --dump-dom \
#    http://www.oddsportal.com/matches/soccer/ > today.html
chromium-browser --headless  --dump-dom \
     http://www.oddsportal.com/matches/soccer/ > today.html

